# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
sudo: false
install:
- R -e 'devtools::install_github("mikelove/fastqcTheoreticalGC")'
notifications:
  recipients:
    - bioinf_hub@adelaide.edu.au
    - christopher.ward@adelaide.edu.au
  email:
    on_success: change
    on_failure: change
