# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
env:
  global:
    - TRAVIS_R_VERSION="3.4.*"
r: 
  - bioc-release
sudo: false
notifications:
  recipients:
    - bioinf_hub@adelaide.edu.au
    - christopher.ward@adelaide.edu.au
  email:
    on_success: change
    on_failure: change
